/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import classes.Aluno;
import classes.ArvoreBinaria;
import classes.iArvore;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import persistencia.ManipulacaoArquivo;

/**
 *
 * @author puc
 */
public class Tela extends javax.swing.JFrame {
    
    private iArvore arvore = null;
    private List<Aluno> listaDeAlunos = null;
    private File arquivoAux = null;
    
    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        this.setLocationRelativeTo(null);
        jButton_Incluir.setEnabled(false);
        jButton_Listar.setEnabled(false);
        jButton_Excluir.setEnabled(false);
        jButton_Buscar.setEnabled(false);
        jComboBox_Ordenacao1.setEnabled(false);
        jComboBox_Ordenacao2.setEnabled(false);
        WindowClosingEventHandler();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }
    
    
    
    private void WindowClosingEventHandler(){
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int resposta = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja fechar?","Confirmação", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION){
                    dispose();
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Incluir = new javax.swing.JButton();
        jButton_Buscar = new javax.swing.JButton();
        jButton_Carregar = new javax.swing.JButton();
        jButton_Listar = new javax.swing.JButton();
        jComboBox_Ordenacao1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Saida = new javax.swing.JTable();
        jComboBox_Ordenacao2 = new javax.swing.JComboBox<>();
        jButton_Excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Tabela de Alunos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton_Incluir.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton_Incluir.setText("Incluir");
        jButton_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IncluirActionPerformed(evt);
            }
        });

        jButton_Buscar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jButton_Carregar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton_Carregar.setText("Carregar");
        jButton_Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CarregarActionPerformed(evt);
            }
        });

        jButton_Listar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton_Listar.setText("Listar");
        jButton_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListarActionPerformed(evt);
            }
        });

        jComboBox_Ordenacao1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jComboBox_Ordenacao1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crescente - Nome", "Decrescente - Nome", "Crescente - Matricula", "Decrescente - Matricula" }));

        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nome", "Turno", "Periodo", "Enfase", "Curso"
            }
        ));
        jTable_Saida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable_SaidaFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Saida);
        if (jTable_Saida.getColumnModel().getColumnCount() > 0) {
            jTable_Saida.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jComboBox_Ordenacao2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jComboBox_Ordenacao2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Curso", "Enfase", "Periodo", "Turno" }));

        jButton_Excluir.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton_Excluir.setText("Excluir");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_Ordenacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jComboBox_Ordenacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jButton_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton_Carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Ordenacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Ordenacao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("UseSpecificCatch")
    private void jButton_CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CarregarActionPerformed
        try{
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Texto", "csv");
            fc.setFileFilter(filtro);
            int res = fc.showOpenDialog(null);
            if (res == JFileChooser.APPROVE_OPTION) {
                File arquivoSelecionado = fc.getSelectedFile();
                arquivoAux = arquivoSelecionado;
                ManipulacaoArquivo lerArquivo = new ManipulacaoArquivo(arquivoAux);
                listaDeAlunos = lerArquivo.getDados();
            }
            if(arquivoAux != null){
                jButton_Carregar.setEnabled(false);
                jButton_Incluir.setEnabled(true);
                jButton_Listar.setEnabled(true);
                jButton_Excluir.setEnabled(true);
                jButton_Buscar.setEnabled(true);
                jComboBox_Ordenacao1.setEnabled(true);
                jComboBox_Ordenacao2.setEnabled(true);
            }
        }
        catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro ao Carregar: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_CarregarActionPerformed

    private void jButton_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListarActionPerformed
         try {
            //if(listaDeAlunos == null) throw new Exception("Lista não Carregada");
            if(arquivoAux == null) throw new Exception("Arquivo não carregado");
            String[] ordenarPor = new String[]{"",""};
            switch(jComboBox_Ordenacao1.getSelectedItem().toString()){
                case "Crescente - Nome":
                    ordenarPor[0] = "Nome";
                    ordenarPor[1] = "Crescente";
                    break;
                case "Decrescente - Nome":
                    ordenarPor[0] = "Nome";
                    ordenarPor[1] = "Decrescente";
                    break;
                case "Crescente - Matricula":
                    ordenarPor[0] = "Matricula";
                    ordenarPor[1] = "Crescente";
                    break;
                case "Decrescente - Matricula":
                    ordenarPor[0] = "Matricula";
                    ordenarPor[1] = "Decrescente";
                    break;
            }
            arvore = new ArvoreBinaria(ordenarPor[0], jComboBox_Ordenacao2.getSelectedItem().toString());
            for(Aluno aluno : listaDeAlunos){
                arvore.incluir(aluno);
            }
            mostrarNaGrid(ordenarPor[1]);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao Listar: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_ListarActionPerformed

    
    private void jButton_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IncluirActionPerformed
        // TODO add your handling code here:
        try{
            //if(listaDeAlunos == null) throw new Exception("Lista não Carregada");
            if(arquivoAux == null) throw new Exception("Arquivo não carregado");
            TelaIncluir telaIncluir = new TelaIncluir();
            telaIncluir.setLista(listaDeAlunos);
            telaIncluir.setVisible(true);
            telaIncluir.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro ao Incluir: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_IncluirActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:
        try {
            //if(listaDeAlunos == null) throw new Exception("Lista não Carregada");
            if(arquivoAux == null) throw new Exception("Arquivo não carregado");
            
            TelaBuscar telaBuscar = new TelaBuscar();
            telaBuscar.setLista(listaDeAlunos);
            telaBuscar.setVisible(true);
            telaBuscar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao Buscar: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        // TODO add your handling code here:
        try {
            //if(listaDeAlunos == null) throw new Exception("Lista não Carregada");
            if(arquivoAux == null) throw new Exception("Arquivo não carregado");
            
            if(jTable_Saida.isEditing()){
                jTable_Saida.getCellEditor().stopCellEditing();
            }
            jTable_Saida.clearSelection();
            jButton_Excluir.requestFocus();
            
            String ordenacao_Nome_Matricula = (jComboBox_Ordenacao1.getSelectedItem().toString().contains("Nome"))? "Nome":"Matricula";
            TelaExcluir telaExcluir = new TelaExcluir();
            telaExcluir.setLista(listaDeAlunos, jComboBox_Ordenacao2.getSelectedItem().toString());
            telaExcluir.setVisible(true);
            telaExcluir.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            telaExcluir.addWindowFocusListener(new WindowFocusListener() {
                @Override
                public void windowGainedFocus(WindowEvent e) {
                    if(jTable_Saida.isEditing()){
                        jTable_Saida.getCellEditor().stopCellEditing();
                    }
                    jTable_Saida.clearSelection();
                }

                @Override
                public void windowLostFocus(WindowEvent e) {
                    
                }
            });
            telaExcluir.addWindowListener(new WindowAdapter(){
                
                @Override
                public void windowClosed(WindowEvent e){
                    try{
                        String opcao_Crescente_Decrescente = (jComboBox_Ordenacao1.getSelectedItem().toString().contains("Crescente"))? "Crescente":"Decrescente";
                        List<Aluno> listaAuxiliar = telaExcluir.getList(opcao_Crescente_Decrescente);
                        arvore = new ArvoreBinaria(ordenacao_Nome_Matricula, jComboBox_Ordenacao2.getSelectedItem().toString());
                        if(arvore != null){
                            for(Aluno aluno : listaAuxiliar){
                                arvore.incluir(aluno);
                            }
                            mostrarNaGrid(opcao_Crescente_Decrescente);
                        }
                    } catch(Exception erro){
                        JOptionPane.showMessageDialog(e.getWindow(), "Erro ao Excluir: " + erro.getMessage());
                    }
                }
            });
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao Buscar: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jTable_SaidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable_SaidaFocusLost
        
    }//GEN-LAST:event_jTable_SaidaFocusLost
    
    
    private void mostrarNaGrid(String opcao){
        try{
            //iArvore arvoreAux = arvore.clonar();
            DefaultTableModel model =  (DefaultTableModel) jTable_Saida.getModel();
            model.setNumRows(0);
            List<Aluno> lista = arvore.getDadosOrdenados(opcao);
            for(Aluno aluno : lista){
                String[] linha = new String[6];
                linha[0] = aluno.getMatricula();
                linha[1] = aluno.getNome();
                linha[2] = aluno.getTurno();
                linha[3] = aluno.getPeriodo()+"";
                linha[4] = aluno.getEnfase();
                linha[5] = aluno.getCurso();
                model.addRow(linha);
            }
        }catch(Exception erro){
            throw erro;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Carregar;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Incluir;
    private javax.swing.JButton jButton_Listar;
    private javax.swing.JComboBox<String> jComboBox_Ordenacao1;
    private javax.swing.JComboBox<String> jComboBox_Ordenacao2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Saida;
    // End of variables declaration//GEN-END:variables
}
