/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author puc
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Questao1 = new javax.swing.JMenuItem();
        Questao2 = new javax.swing.JMenuItem();
        Questao3 = new javax.swing.JMenuItem();
        Questao4 = new javax.swing.JMenuItem();
        Questao5 = new javax.swing.JMenuItem();
        Questao6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Painel.setBackground(new java.awt.Color(112, 140, 192));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Exercícios de Recursividade");

        Painel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLayout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 538, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        Questao1.setText("Questão 1");
        Questao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Questao1ActionPerformed(evt);
            }
        });
        jMenu1.add(Questao1);

        Questao2.setText("Questão 2");
        Questao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Questao2ActionPerformed(evt);
            }
        });
        jMenu1.add(Questao2);

        Questao3.setText("Questão 3");
        Questao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Questao3ActionPerformed(evt);
            }
        });
        jMenu1.add(Questao3);

        Questao4.setText("Questão 4");
        Questao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Questao4ActionPerformed(evt);
            }
        });
        jMenu1.add(Questao4);

        Questao5.setText("Questão 5");
        Questao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Questao5ActionPerformed(evt);
            }
        });
        jMenu1.add(Questao5);

        Questao6.setText("Questão 6");
        Questao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Questao6ActionPerformed(evt);
            }
        });
        jMenu1.add(Questao6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Questao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Questao1ActionPerformed
        // TODO add your handling code here:
        Questao1 obj = new Questao1();
        Painel.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_Questao1ActionPerformed

    private void Questao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Questao2ActionPerformed
        // TODO add your handling code here:
        Questao2 obj = new Questao2();
        Painel.add(obj);
        obj.setVisible(true);
                              
    }//GEN-LAST:event_Questao2ActionPerformed

    private void Questao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Questao3ActionPerformed
        // TODO add your handling code here:
        Questao3 obj = new Questao3();
        Painel.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_Questao3ActionPerformed

    private void Questao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Questao4ActionPerformed
        // TODO add your handling code here:
        Questao4 obj = new Questao4();
        Painel.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_Questao4ActionPerformed

    private void Questao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Questao5ActionPerformed
        // TODO add your handling code here:
        Questao5 obj = new Questao5();
        Painel.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_Questao5ActionPerformed

    private void Questao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Questao6ActionPerformed
        // TODO add your handling code here:
        Questao6 obj = new Questao6();
        Painel.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_Questao6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Painel;
    private javax.swing.JMenuItem Questao1;
    private javax.swing.JMenuItem Questao2;
    private javax.swing.JMenuItem Questao3;
    private javax.swing.JMenuItem Questao4;
    private javax.swing.JMenuItem Questao5;
    private javax.swing.JMenuItem Questao6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
