
package visaoNaturais;
import entidades.calculadoraNaturais;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaPrincipalNaturais extends javax.swing.JFrame {
    /**
     * Creates new form TelaPrincipalNaturais
     */
    public TelaPrincipalNaturais() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel_numero1 = new javax.swing.JLabel();
        jLabel_numero2 = new javax.swing.JLabel();
        jTextField_numero1 = new javax.swing.JTextField();
        jTextField_numero2 = new javax.swing.JTextField();
        jButton_executar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Saida = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_titulo.setText("Cálculos para Números Naturais");

        jLabel_numero1.setText("Número 1:");

        jLabel_numero2.setText("Número 2:");

        jButton_executar.setText("Executar");
        jButton_executar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_executarActionPerformed(evt);
            }
        });

        jTable_Saida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Saida.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable_Saida.setShowGrid(true);
        jScrollPane2.setViewportView(jTable_Saida);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tarefas POO_resized_resized_resized.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/flamengo-logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_numero1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_numero2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_executar)
                                    .addComponent(jTextField_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_numero1)
                            .addComponent(jTextField_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_numero2))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_executar)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_executarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_executarActionPerformed
        try {
            long numero1 = Long.parseLong(jTextField_numero1.getText());
            long numero2 = Long.parseLong(jTextField_numero2.getText());
            calculadoraNaturais calcular = new calculadoraNaturais(numero1, numero2);
        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {"ITEM", "Numero1", "Numero2"}
            ));
        
        DefaultTableModel model =  (DefaultTableModel) jTable_Saida.getModel();
            String[][] dados = {
                {"Fatorial", String.valueOf(calcular.fatorial(numero1)), String.valueOf(calcular.fatorial(numero2))},
                {"Número Perfeito", String.valueOf(calcular.numeroPerfeito(numero1)), String.valueOf(calcular.numeroPerfeito(numero2))},
                {"Capicua", String.valueOf(calcular.capicua(numero1)), String.valueOf(calcular.capicua(numero2))},
                {"Quadrado Perfeito", String.valueOf(calcular.quadradoPerfeito(numero1)), String.valueOf(calcular.quadradoPerfeito(numero2)) },
                {"Número Primo", String.valueOf(calcular.primo(numero1)), String.valueOf(calcular.primo(numero2))},
                {"Base 10 para Base 2", String.valueOf(calcular.base2(numero1)), String.valueOf(calcular.base2(numero2))},
                {"Base 10 para Base 8", String.valueOf(calcular.base8(numero1)), String.valueOf(calcular.base8(numero2))},
                {"Base 10 para Base 16", String.valueOf(calcular.base16(numero1)), String.valueOf(calcular.base16(numero2))},
                {"Máximo Divisor Comum", String.valueOf(calcular.mdc(numero1, numero2)), String.valueOf(calcular.mdc(numero1, numero2))},
                {"Mínimo Múltiplo Comum", String.valueOf(calcular.mmc(numero1, numero2)), String.valueOf(calcular.mmc(numero1, numero2))},
                {"Primo entre Si", String.valueOf(calcular.primosEntreSi(numero1, numero2)), String.valueOf(calcular.primosEntreSi(numero1, numero2))}
                   
            };
        for (String[] saida : dados) {
    model.addRow(saida);
        }
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(this, erro.getMessage());
    }
    }//GEN-LAST:event_jButton_executarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalNaturais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalNaturais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalNaturais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalNaturais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalNaturais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_executar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_numero1;
    private javax.swing.JLabel jLabel_numero2;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Saida;
    private javax.swing.JTextField jTextField_numero1;
    private javax.swing.JTextField jTextField_numero2;
    // End of variables declaration//GEN-END:variables
}
