/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelos.Professor;
import Interface.IProfessor;
import java.util.LinkedList;
import persistencia.ManipArq;
import visao.MultiLineTableCellRenderer;


public class TelaPrincipal extends javax.swing.JFrame {
    IProfessor professor = null;
    int coliso = 0;
public enum titulacao {

    DOUTOR("Doutor(a)"),
    MESTRE("Mestre(a)"),
    ESPECIALISTA("Especialista"),
    POS_DOUTOR("Pos-Doutor(a)"),
    BACHARELADO("Bacharelado");
    
    private String descricao;

    titulacao(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricao() {
        return descricao;
    }
}

public enum contrato {

    TI("TI"),
    HORISTA("Horista");
    
    private String descricao;

    contrato(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricao() {
        return descricao;
    }
}
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jButton_Excluir.setEnabled(false);
        jButton_Alterar.setEnabled(false);
        jButton_Incluir.setEnabled(false);
        jTextField_Nome.setEnabled(false);
        jTextField_Matricula.setEnabled(false);
        jTextField_Escola.setEnabled(false);
        jComboBox_Contrato.setEnabled(false);
        jComboBox_Titulacao.setEnabled(false);
        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {"Posicao","Professor"}
        ));
        jComboBox_Titulacao.setModel(new javax.swing.DefaultComboBoxModel(titulacao.values()));
        jComboBox_Contrato.setModel(new javax.swing.DefaultComboBoxModel(contrato.values()));
    }
    private void listarClientes(){
    try {
        LinkedList<Professor>[] array = professor.listar();
        jTable_Saida.setRowHeight(100);
        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {"Posicao"}
        ));
        DefaultTableModel model = (DefaultTableModel) jTable_Saida.getModel();
        int tamanh = coliso;
        tamanh++;
        String[] saida = new String[tamanh];
        int profTabela = 0;
        tamanh--;
        for(int i = 0;i < tamanh; i++){
        profTabela = i;
        profTabela++;
        model.addColumn("Professor"+" "+"("+(profTabela)+")");
        }  
        for (int i = 0; i < tamanh+1; i++) {
              jTable_Saida.getColumnModel().getColumn(i).setCellRenderer(new MultiLineTableCellRenderer());
          }
        model.setNumRows(0);
        int size;
        int c = 1;
        size = array.length;
        for(int i = 0;i < size; i++){
            saida[0] = i + "";
            for(int j = 0;j < tamanh; j++){
            if((array[i].get(j)) != null){
            saida[c] = array[i].get(j).toString();
            }
            else{
            saida[c] = "";
            }
            c++;
            }
            model.addRow(saida);
            c = 1;
        }
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();
        jTextField_Matricula = new javax.swing.JTextField();
        jTextField_Escola = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Saida = new javax.swing.JTable();
        jButton_Incluir = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jButton_Alterar = new javax.swing.JButton();
        jButton_CarregarArq = new javax.swing.JButton();
        jComboBox_Titulacao = new javax.swing.JComboBox<>();
        jComboBox_Contrato = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("MATRICULA:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("NOME:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("ESCOLA:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("TITULACAO:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("CONTRATO:");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SISTEMA DE CONTROLE E DE PROFESSORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/escudo-flamengo-3-768x935 (2).png"))); // NOI18N

        jTextField_Nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_Matricula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_Escola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable_Saida.setBackground(new java.awt.Color(0, 0, 0));
        jTable_Saida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Saida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SaidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Saida);

        jButton_Incluir.setBackground(new java.awt.Color(204, 0, 0));
        jButton_Incluir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton_Incluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-soma-30.png"))); // NOI18N
        jButton_Incluir.setText("INCLUIR");
        jButton_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IncluirActionPerformed(evt);
            }
        });

        jButton_Excluir.setBackground(new java.awt.Color(204, 0, 0));
        jButton_Excluir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton_Excluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-lixeira-30.png"))); // NOI18N
        jButton_Excluir.setText("EXCLUIR");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jButton_Alterar.setBackground(new java.awt.Color(204, 0, 0));
        jButton_Alterar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton_Alterar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-lápis-30.png"))); // NOI18N
        jButton_Alterar.setText("ALTERAR");
        jButton_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AlterarActionPerformed(evt);
            }
        });

        jButton_CarregarArq.setBackground(new java.awt.Color(0, 153, 0));
        jButton_CarregarArq.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton_CarregarArq.setForeground(new java.awt.Color(255, 255, 255));
        jButton_CarregarArq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadora-simples (1).png"))); // NOI18N
        jButton_CarregarArq.setText("CARREGAR");
        jButton_CarregarArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CarregarArqActionPerformed(evt);
            }
        });

        jComboBox_Titulacao.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jComboBox_Titulacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Titulacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_TitulacaoMouseClicked(evt);
            }
        });
        jComboBox_Titulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TitulacaoActionPerformed(evt);
            }
        });

        jComboBox_Contrato.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jComboBox_Contrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox_Titulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Escola, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox_Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Incluir)
                        .addGap(97, 97, 97)
                        .addComponent(jButton_Excluir)
                        .addGap(88, 88, 88)
                        .addComponent(jButton_Alterar)
                        .addGap(47, 47, 47)
                        .addComponent(jButton_CarregarArq)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Escola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Titulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Incluir)
                    .addComponent(jButton_Excluir)
                    .addComponent(jButton_Alterar)
                    .addComponent(jButton_CarregarArq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IncluirActionPerformed
        // TODO add your handling code here:
        try {
            if(jTextField_Matricula.getText().isEmpty()) throw new Exception("Esse campo (Matricula) nao pode estar vazio.");
           if(!jTextField_Matricula.getText().matches("[0-9]+")) throw new Exception ("Esse campo (Matricula) somente aceita numeros.");            
           Professor novoProfessor = new Professor(Integer.parseInt(jTextField_Matricula.getText()), jTextField_Nome.getText().toUpperCase(), jTextField_Escola.getText().toUpperCase(), titulacao.valueOf(jComboBox_Titulacao.getSelectedItem().toString()).getDescricao(), contrato.valueOf(jComboBox_Contrato.getSelectedItem().toString()).getDescricao());
            professor.incluir(novoProfessor);
            listarClientes();
            jTextField_Nome.setText("");
            jTextField_Matricula.setText("");
            jTextField_Escola.setText("");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage() + " Incluir");
        }
    }//GEN-LAST:event_jButton_IncluirActionPerformed

    private void jButton_CarregarArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CarregarArqActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("text","csv");
        fc.setFileFilter(filtro);
        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();
            ManipArq dados = new ManipArq(arquivo);
            try {
                professor = dados.obterProfess();
                coliso = (dados.obterProfess().getColisoes());
            } catch (Exception e) {
            }
            listarClientes();
            jButton_Incluir.setEnabled(true);
            jTextField_Nome.setEnabled(true);
            jTextField_Matricula.setEnabled(true);
            jTextField_Escola.setEnabled(true);
            jComboBox_Contrato.setEnabled(true);
            jComboBox_Titulacao.setEnabled(true);
        }
    }//GEN-LAST:event_jButton_CarregarArqActionPerformed

    private void jComboBox_TitulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TitulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TitulacaoActionPerformed

    private void jComboBox_TitulacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_TitulacaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TitulacaoMouseClicked

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        // TODO add your handling code here:
                try {
            if((JOptionPane.showConfirmDialog(null,"Voce deseja realmente remover esse contato?", "Remover Contato",JOptionPane.YES_NO_OPTION)) == JOptionPane.YES_OPTION){
            int matricula = Integer.parseInt(jTextField_Matricula.getText());
            professor.excluir(matricula);
            listarClientes();
            }
            
            jTextField_Nome.setText("");
            jTextField_Matricula.setText("");
            jTextField_Escola.setText("");
            
            jTextField_Matricula.setEnabled(true); 
            jTextField_Nome.setEnabled(true);
            jButton_CarregarArq.setEnabled(true);
            jComboBox_Titulacao.setEnabled(true);
            jTextField_Escola.setEnabled(true);
            jComboBox_Contrato.setEnabled(true);
            
            jButton_Excluir.setEnabled(false);
            jButton_Alterar.setEnabled(false);
            jButton_Incluir.setEnabled(true);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }      
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jTable_SaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SaidaMouseClicked
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) jTable_Saida.getModel(); 
        int linhaselecionada = jTable_Saida.getSelectedRow();
        String tabela = (String) model.getValueAt(linhaselecionada,jTable_Saida.getSelectedColumn());
        String[] partesLinha = tabela.split("\n");
        
        String[] partesLinha2 = (partesLinha[0]).split(":");
        jTextField_Matricula.setText(partesLinha2[1]); 
        
        String[] partesLinha3 = (partesLinha[1]).split(":");
        jTextField_Nome.setText(partesLinha3[1]);
        
        String[] partesLinha4 = (partesLinha[2]).split(":");
        jTextField_Escola.setText(partesLinha4[1]);
        jComboBox_Titulacao.setEnabled(false);
        jComboBox_Contrato.setEnabled(false);
        jButton_CarregarArq.setEnabled(false);
        
        jButton_Incluir.setEnabled(false);
        jTextField_Matricula.setEnabled(false); 
        jTextField_Nome.setEnabled(false);
        jTextField_Escola.setEnabled(false);
        jButton_Excluir.setEnabled(true);
        jButton_Alterar.setEnabled(true);
    }//GEN-LAST:event_jTable_SaidaMouseClicked

    private void jButton_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AlterarActionPerformed
        // TODO add your handling code here:
        try {
            if(!jTextField_Nome.isEnabled()){
                jTextField_Matricula.setEnabled(false);
                jButton_Excluir.setEnabled(false);
                jTextField_Nome.setEnabled(true);
                jTextField_Escola.setEnabled(true);
                jComboBox_Contrato.setEnabled(true);
                jComboBox_Titulacao.setEnabled(true);
                jButton_Incluir.setEnabled(false);
                jButton_CarregarArq.setEnabled(false); 
            }
            else{
                if((JOptionPane.showConfirmDialog(null,"Voce deseja realmente alterar esse contato?", "Alterar Contato",JOptionPane.YES_NO_OPTION)) == JOptionPane.YES_OPTION){
                Professor novoProfessor = new Professor(Integer.parseInt(jTextField_Matricula.getText()), jTextField_Nome.getText().toUpperCase(), jTextField_Escola.getText().toUpperCase(), titulacao.valueOf(jComboBox_Titulacao.getSelectedItem().toString()).getDescricao(), contrato.valueOf(jComboBox_Contrato.getSelectedItem().toString()).getDescricao());
                professor.alterar(novoProfessor);
                listarClientes();
                
                jButton_Incluir.setEnabled(true);
                jTextField_Matricula.setEnabled(true);
                jTextField_Nome.setEnabled(true);
                jButton_CarregarArq.setEnabled(true);
                jButton_Excluir.setEnabled(false);
                jButton_Alterar.setEnabled(false);
                jTextField_Nome.setText("");
                jTextField_Matricula.setText("");
                jTextField_Escola.setText("");
                }
                
                else{
                jButton_Incluir.setEnabled(true);
                jTextField_Matricula.setEnabled(true);
                jTextField_Nome.setEnabled(true);
                jButton_CarregarArq.setEnabled(true);
                jButton_Excluir.setEnabled(false);
                jButton_Alterar.setEnabled(false);
                jTextField_Nome.setText("");
                jTextField_Matricula.setText("");
                jTextField_Escola.setText("");
                }
            }
        
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Alterar;
    private javax.swing.JButton jButton_CarregarArq;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Incluir;
    private javax.swing.JComboBox<String> jComboBox_Contrato;
    private javax.swing.JComboBox<String> jComboBox_Titulacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Saida;
    private javax.swing.JTextField jTextField_Escola;
    private javax.swing.JTextField jTextField_Matricula;
    private javax.swing.JTextField jTextField_Nome;
    // End of variables declaration//GEN-END:variables
}
