/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import modelos.Icrud;
import controle.ContatoCTL;
import java.util.List;
import javax.swing.JOptionPane;
import modelos.Contato;
import persistencia.ContatoDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eugen
 */
public class TelaPrincipal extends javax.swing.JFrame {
    //Atributo da Controle
    Icrud objContatoCTL = new ContatoCTL();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private void mostrarListaDeContatos() throws Exception{
      try {
        ContatoDAO objetoContatoDao = new ContatoDAO();
        List<Contato> listaDeContatos = objetoContatoDao.listagemDeContatos();
        DefaultTableModel model =  (DefaultTableModel) jTableDadosDosContatos.getModel();
        model.setNumRows(0);
        if(listaDeContatos.isEmpty()) return;
        for(int pos = 0; pos < listaDeContatos.size(); pos++){
          Contato pessoa = listaDeContatos.get(pos);
          String[] linha = new String[3];
          linha[0]= pessoa.getNomeCompleto();
          linha[1]= pessoa.getTelefone();
          linha[2] = pessoa.getEmail();
          model.addRow(linha);
        }
      } catch (Exception erro) {
        throw erro;
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelPrincipal = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanelDosDados = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jTextFieldNomeCompleto = new javax.swing.JTextField();
    jTextFieldEmail = new javax.swing.JTextField();
    jTextFieldTelefone1 = new javax.swing.JTextField();
    jPanelAcoes = new javax.swing.JPanel();
    jButtonIncluir = new javax.swing.JButton();
    jButtonExcluir = new javax.swing.JButton();
    jButtonConsultar = new javax.swing.JButton();
    jButtonAlterar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTableDadosDosContatos = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("SISTEMA DE CONTROLE DA AGENDA DE CONTATOS");

    jPanelPrincipal.setBackground(new java.awt.Color(0, 102, 102));
    jPanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("AGENDA DE CONTATOS");

    javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
    jPanelPrincipal.setLayout(jPanelPrincipalLayout);
    jPanelPrincipalLayout.setHorizontalGroup(
      jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelPrincipalLayout.createSequentialGroup()
        .addGap(320, 320, 320)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanelPrincipalLayout.setVerticalGroup(
      jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelPrincipalLayout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(jLabel1)
        .addContainerGap(20, Short.MAX_VALUE))
    );

    jPanelDosDados.setBackground(new java.awt.Color(51, 153, 255));

    jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
    jLabel2.setText("TELEFONE");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
    jLabel3.setText("NOME COMPLETO");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
    jLabel4.setText("E-MAIL");

    jTextFieldNomeCompleto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

    jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

    jTextFieldTelefone1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

    jPanelAcoes.setBackground(new java.awt.Color(102, 102, 102));

    jButtonIncluir.setBackground(new java.awt.Color(255, 255, 0));
    jButtonIncluir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
    jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/iconeA_16.png"))); // NOI18N
    jButtonIncluir.setText("INCLUIR");
    jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonIncluirActionPerformed(evt);
      }
    });

    jButtonExcluir.setBackground(new java.awt.Color(255, 255, 0));
    jButtonExcluir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
    jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/excluir16.png"))); // NOI18N
    jButtonExcluir.setText("EXCLUIR");

    jButtonConsultar.setBackground(new java.awt.Color(255, 255, 0));
    jButtonConsultar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
    jButtonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/buscar16.png"))); // NOI18N
    jButtonConsultar.setText("CONSULTAR");
    jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonConsultarActionPerformed(evt);
      }
    });

    jButtonAlterar.setBackground(new java.awt.Color(255, 255, 0));
    jButtonAlterar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
    jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/iconeC_16.png"))); // NOI18N
    jButtonAlterar.setText("ALTERAR");

    javax.swing.GroupLayout jPanelAcoesLayout = new javax.swing.GroupLayout(jPanelAcoes);
    jPanelAcoes.setLayout(jPanelAcoesLayout);
    jPanelAcoesLayout.setHorizontalGroup(
      jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAcoesLayout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jButtonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(37, 37, 37))
    );
    jPanelAcoesLayout.setVerticalGroup(
      jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAcoesLayout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonIncluir)
          .addComponent(jButtonConsultar))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonExcluir)
          .addComponent(jButtonAlterar))
        .addGap(29, 29, 29))
    );

    javax.swing.GroupLayout jPanelDosDadosLayout = new javax.swing.GroupLayout(jPanelDosDados);
    jPanelDosDados.setLayout(jPanelDosDadosLayout);
    jPanelDosDadosLayout.setHorizontalGroup(
      jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelDosDadosLayout.createSequentialGroup()
        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanelDosDadosLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(jPanelDosDadosLayout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(32, 32, 32)
        .addComponent(jPanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(100, Short.MAX_VALUE))
    );
    jPanelDosDadosLayout.setVerticalGroup(
      jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelDosDadosLayout.createSequentialGroup()
        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanelDosDadosLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDosDadosLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jTextFieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2)
              .addComponent(jTextFieldTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(30, Short.MAX_VALUE))
    );

    jTableDadosDosContatos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "NOME COMPLETO", "TELEFFONE", "E-MAIL"
      }
    ));
    jScrollPane1.setViewportView(jTableDadosDosContatos);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanelDosDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanelDosDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 31, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
    // TODO add your handling code here:
    try {
      Contato objetoContato = null;
      String nome = jTextFieldNomeCompleto.getText();
      String telefone = jTextFieldTelefone1.getText();
      String email = jTextFieldEmail.getText();
      objetoContato = new Contato(nome,telefone,email);
      ContatoDAO objetoContatoDao = new ContatoDAO();
      objetoContatoDao.incluir(objetoContato);
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(null, erro.getMessage());
    }
  }//GEN-LAST:event_jButtonIncluirActionPerformed

  private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
    // TODO add your handling code here:
    try {
      ContatoDAO objetoContatoDao = new ContatoDAO();
      List<Contato> listaDeContatos = objetoContatoDao.listagemDeContatos();
      int quantidade = listaDeContatos.size();
      JOptionPane.showMessageDialog(null,"Quantidade: " + quantidade);
      mostrarListaDeContatos();
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(null, erro.getMessage());
    }
    
  }//GEN-LAST:event_jButtonConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAlterar;
  private javax.swing.JButton jButtonConsultar;
  private javax.swing.JButton jButtonExcluir;
  private javax.swing.JButton jButtonIncluir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanelAcoes;
  private javax.swing.JPanel jPanelDosDados;
  private javax.swing.JPanel jPanelPrincipal;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableDadosDosContatos;
  private javax.swing.JTextField jTextFieldEmail;
  private javax.swing.JTextField jTextFieldNomeCompleto;
  private javax.swing.JTextField jTextFieldTelefone1;
  // End of variables declaration//GEN-END:variables
}
