/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import entidade.ConjuntoDosNumerosNaturais;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pedro Francisco
 */
public class TelaDoProjetoConjuntoDosNúmerosNaturais extends javax.swing.JFrame {
    public String booleanToString(boolean valor){
        return valor ? "sim" : "não";
    }

    /**
     * Creates new form TeladoProjetoConjuntoDosNúmerosNaturais
     */
    public TelaDoProjetoConjuntoDosNúmerosNaturais() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPrimeiroNumeroNatural = new javax.swing.JTextField();
        txtSegundoNumeroNatural = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblTabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Conjunto dos Numeros Naturais ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Primeiro Numero Natural: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Segundo Numero Natural: ");

        lblTabela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"FATURA", null, null},
                {"NUMERO PERFEITO", null, null},
                {"CAPICUA", null, null},
                {"QUADRADO PERFEITO", null, null},
                {"NUMERO PRIMO", null, null},
                {"BASE 10 PARA BASE 2", null, null},
                {"BASE 10 PARA BASE 8", null, null},
                {"BASE 10 PARA BASE 16", null, null},
                {"MAXIMO DIVISOR COMUM", null, null},
                {"MINIMO MULTIPLO COMUM", null, null},
                {"PRIMOS ENTRE SI", null, null}
            },
            new String [] {
                "ITEM", "NUMERO NATURAL:", "NUMERO NATURAL:"
            }
        ));
        jScrollPane1.setViewportView(lblTabela);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/foto.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("João Marcelo Angeli Barbosa");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pucgoias.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrimeiroNumeroNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSegundoNumeroNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtPrimeiroNumeroNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtSegundoNumeroNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addComponent(jButton1))))
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            long numero1 = Long.parseLong(txtPrimeiroNumeroNatural.getText());
            long numero2 = Long.parseLong(txtSegundoNumeroNatural.getText());
            ConjuntoDosNumerosNaturais n1 = new ConjuntoDosNumerosNaturais(numero1);
             ConjuntoDosNumerosNaturais n2 = new ConjuntoDosNumerosNaturais(numero2);
        lblTabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {"ITEM", "NUMERO NATURAL: "+numero1, "NUMERO NATURAL: "+numero2}
            ));
        
        DefaultTableModel model =  (DefaultTableModel) lblTabela.getModel();
        String[][] dados = {
                {"Fatorial", String.valueOf(n1.fatorial(numero1)), String.valueOf(n2.fatorial(numero2))},
            
                {"Número Perfeito", booleanToString(n1.numeroPerfeito(numero1)), booleanToString(n2.numeroPerfeito(numero2))},
                
                {"Capicua", booleanToString(n1.capicua(numero1)), booleanToString(n2.capicua(numero2))},
                
                {"Quadrado Perfeito", booleanToString(n1.quadradoPerfeito(numero1)), booleanToString(n2.quadradoPerfeito(numero2)) },
                
                {"Número Primo", booleanToString(n1.primo(numero1)), booleanToString(n2.primo(numero2))},
                
                {"Base 10 para Base 2", String.valueOf(n1.mudarBase(2)), String.valueOf(n2.mudarBase(2))},
                
                {"Base 10 para Base 8", String.valueOf(n1.mudarBase(8)), String.valueOf(n2.mudarBase(8))},
                
                {"Base 10 para Base 16", String.valueOf(n1.mudarBase(16)), String.valueOf(n2.mudarBase(16))},
                
                {"Máximo Divisor Comum", String.valueOf(n1.mdc(numero1, numero2)), String.valueOf(n2.mdc(numero1, numero2))},
                
                {"Mínimo Múltiplo Comum", String.valueOf(n1.mmc(numero1, numero2)), String.valueOf(n2.mmc(numero1, numero2))},
                
                {"Primo entre Si", booleanToString(n1.primosEntreSi(numero1, numero2)), booleanToString(n2.primosEntreSi(numero1, numero2))}
                   
            };
        for (String[] saida : dados) {
    model.addRow(saida);
        }
    }
        catch (Exception erro) {
      JOptionPane.showMessageDialog(this, erro.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoProjetoConjuntoDosNúmerosNaturais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoProjetoConjuntoDosNúmerosNaturais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoProjetoConjuntoDosNúmerosNaturais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoProjetoConjuntoDosNúmerosNaturais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoProjetoConjuntoDosNúmerosNaturais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lblTabela;
    private javax.swing.JTextField txtPrimeiroNumeroNatural;
    private javax.swing.JTextField txtSegundoNumeroNatural;
    // End of variables declaration//GEN-END:variables
}
